import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:pmtiles/pmtiles.dart';
import 'package:vector_map_tiles/vector_map_tiles.dart';
import 'package:vector_tile_renderer/vector_tile_renderer.dart' as vtr;

import 'parcel_lookup_service.dart';

/// Thrown when a basemap download is cancelled by the caller.
class VectorBasemapDownloadCancelled implements Exception {
  const VectorBasemapDownloadCancelled();
}

/// Loads and serves the vector basemap: the Slovenia PMTiles archive (Organic
/// Maps data, hosted on R2) read over HTTP range requests, themed with the
/// MapLibre style ported from OM's cartography (bundled as an asset).
///
/// The archive and theme are loaded once on first use; until [isReady] the map
/// falls back to whatever raster base was previously shown.
class VectorBasemapService extends ChangeNotifier {
  VectorBasemapService._();
  static final VectorBasemapService instance = VectorBasemapService._();

  /// Bundled MapLibre style (generated by tools/mwm2pmtiles/port_style.py).
  static const _styleAsset = 'assets/gozdar_basemap_style.json';

  /// Source id in the style — the [TileProviders] key must match it.
  static const _sourceName = 'gozdar';

  /// Local filename for the fully downloaded archive (offline use).
  static const _localFileName = 'slovenia.pmtiles';

  static String get _pmtilesUrl =>
      '${ParcelLookupService.r2BaseUrl}/$_localFileName';

  bool _loading = false;
  bool _ready = false;
  String? _error;

  /// True when the loaded archive is being read from the local file rather than
  /// streamed from the network.
  bool _offline = false;

  bool _downloading = false;

  /// Cached existence of the local copy, refreshed at startup and on
  /// download/remove. Lets the UI gate the layer synchronously.
  bool _hasLocal = false;

  TileProviders? _tileProviders;
  vtr.Theme? _theme;
  String? _localPathCache;

  /// True once the archive + theme are loaded and the layer can render.
  bool get isReady => _ready;

  /// True when serving from the fully downloaded local archive.
  bool get isOffline => _offline;

  /// True while a full download is in progress.
  bool get isDownloading => _downloading;

  /// Last error, if any (null while loading or after success).
  String? get error => _error;

  TileProviders? get tileProviders => _tileProviders;
  vtr.Theme? get theme => _theme;

  Future<String> _localPath() async =>
      _localPathCache ??=
          '${(await getApplicationSupportDirectory()).path}/$_localFileName';

  /// Synchronously-readable cache of [isDownloaded], for gating the layer in the
  /// selector. Call [refreshLocal] once at startup to populate it.
  bool get hasLocalCopy => _hasLocal;

  /// Whether a full local copy has been downloaded.
  Future<bool> isDownloaded() async => File(await _localPath()).exists();

  /// Refresh [hasLocalCopy] from disk and notify listeners.
  Future<void> refreshLocal() async {
    final exists = await File(await _localPath()).exists();
    if (exists != _hasLocal) {
      _hasLocal = exists;
      notifyListeners();
    }
  }

  /// Size of the downloaded archive in bytes, or null when not downloaded.
  Future<int?> downloadedSizeBytes() async {
    final f = File(await _localPath());
    return (await f.exists()) ? f.length() : null;
  }

  /// Open the archive and read the theme. Prefers the fully downloaded local
  /// file; otherwise streams from the network over HTTP range requests.
  /// Idempotent and safe to call from build(); notifies listeners when ready.
  Future<void> ensureLoaded() async {
    if (_ready || _loading) return;
    _loading = true;
    try {
      final path = await _localPath();
      final local = await File(path).exists();
      final archive = local
          ? await PmTilesArchive.fromFile(File(path))
          : await PmTilesArchive.from(_pmtilesUrl);
      final provider = _PmTilesVectorTileProvider(
        archive,
        minimumZoom: archive.header.minZoom,
        maximumZoom: archive.header.maxZoom,
      );
      final styleText = await rootBundle.loadString(_styleAsset);
      _theme = vtr.ThemeReader().read(
        json.decode(styleText) as Map<String, dynamic>,
      );
      _tileProviders = TileProviders({_sourceName: provider});
      _offline = local;
      _ready = true;
      _error = null;
    } catch (e) {
      _error = '$e';
      debugPrint('VectorBasemapService: load failed: $e');
    } finally {
      _loading = false;
      notifyListeners();
    }
  }

  /// Fully download the archive for offline use, then reopen from the local
  /// file. Reports progress via [onProgress]; throws
  /// [VectorBasemapDownloadCancelled] if [isCancelled] returns true mid-stream.
  Future<void> download({
    void Function(int received, int? total)? onProgress,
    bool Function()? isCancelled,
  }) async {
    if (_downloading) return;
    _downloading = true;
    _error = null;
    notifyListeners();
    final target = await _localPath();
    final part = File('$target.part');
    final client = http.Client();
    try {
      if (await part.exists()) await part.delete();
      final response =
          await client.send(http.Request('GET', Uri.parse(_pmtilesUrl)));
      if (response.statusCode != 200) {
        throw FormatException('Prenos ni uspel (HTTP ${response.statusCode}).');
      }
      final total = response.contentLength;
      var received = 0;
      final sink = part.openWrite();
      try {
        await for (final chunk in response.stream) {
          if (isCancelled?.call() ?? false) {
            throw const VectorBasemapDownloadCancelled();
          }
          sink.add(chunk);
          received += chunk.length;
          onProgress?.call(received, total);
        }
      } finally {
        await sink.close();
      }
      await part.rename(target);
      _hasLocal = true;
      // Reopen from the local file so the map switches to offline immediately.
      _ready = false;
      _tileProviders = null;
      _theme = null;
      await ensureLoaded();
    } finally {
      _downloading = false;
      client.close();
      if (await part.exists()) {
        try {
          await part.delete();
        } catch (_) {}
      }
      notifyListeners();
    }
  }

  /// Delete the local copy and fall back to streaming on next load.
  Future<void> removeDownload() async {
    final f = File(await _localPath());
    if (await f.exists()) await f.delete();
    _hasLocal = false;
    _ready = false;
    _offline = false;
    _tileProviders = null;
    _theme = null;
    notifyListeners();
  }
}

/// Reads MVT tiles for [VectorTileLayer] from a PMTiles archive. PMTiles stores
/// tiles by Hilbert-curve id and (usually) gzip-compressed; [Tile.bytes]
/// decompresses to raw pbf. Missing/sparse tiles render as empty rather than
/// failing the whole layer.
class _PmTilesVectorTileProvider implements VectorTileProvider {
  final PmTilesArchive _archive;

  @override
  final int minimumZoom;
  @override
  final int maximumZoom;

  _PmTilesVectorTileProvider(
    this._archive, {
    required this.minimumZoom,
    required this.maximumZoom,
  });

  @override
  TileProviderType get type => TileProviderType.vector;

  @override
  TileOffset get tileOffset => TileOffset.DEFAULT;

  @override
  Future<Uint8List> provide(TileIdentity tile) async {
    if (tile.z < minimumZoom || tile.z > maximumZoom) return Uint8List(0);
    try {
      final id = ZXY(tile.z, tile.x, tile.y).toTileId();
      final t = await _archive.tile(id);
      return Uint8List.fromList(t.bytes());
    } catch (_) {
      // Tile absent in the (sparse) archive or unreadable — draw nothing.
      return Uint8List(0);
    }
  }
}
