// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfVBmc5cUlX34H7u9AVZUUsg-njJHn_RY',
    appId: '1:1071918678812:web:7e7ef8c83b78fa7bb1f0d9',
    messagingSenderId: '1071918678812',
    projectId: 'gozdar-bb8e2',
    authDomain: 'gozdar-bb8e2.firebaseapp.com',
    storageBucket: 'gozdar-bb8e2.firebasestorage.app',
    measurementId: 'G-2WEXXCBHHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJdr8HhQwXl25CDzcGGvdvsngZumUmYBs',
    appId: '1:1071918678812:android:623ea322e1763ee0b1f0d9',
    messagingSenderId: '1071918678812',
    projectId: 'gozdar-bb8e2',
    storageBucket: 'gozdar-bb8e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDY_dg_EciIQst9UyMf_iM01vihrzmr3w',
    appId: '1:1071918678812:ios:9dce461d79faac5eb1f0d9',
    messagingSenderId: '1071918678812',
    projectId: 'gozdar-bb8e2',
    storageBucket: 'gozdar-bb8e2.firebasestorage.app',
    iosBundleId: 'dev.dz0ny.gozdar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDY_dg_EciIQst9UyMf_iM01vihrzmr3w',
    appId: '1:1071918678812:ios:9dce461d79faac5eb1f0d9',
    messagingSenderId: '1071918678812',
    projectId: 'gozdar-bb8e2',
    storageBucket: 'gozdar-bb8e2.firebasestorage.app',
    iosBundleId: 'dev.dz0ny.gozdar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfVBmc5cUlX34H7u9AVZUUsg-njJHn_RY',
    appId: '1:1071918678812:web:54d08fbca4642688b1f0d9',
    messagingSenderId: '1071918678812',
    projectId: 'gozdar-bb8e2',
    authDomain: 'gozdar-bb8e2.firebaseapp.com',
    storageBucket: 'gozdar-bb8e2.firebasestorage.app',
    measurementId: 'G-SXBWKZNVX6',
  );
}
