// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/http_cache_entry.dart';
import 'models/imported_overlay.dart';
import 'models/log_batch.dart';
import 'models/log_entry.dart';
import 'models/map_location.dart';
import 'models/parcel.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4658729384674843745),
    name: 'LogBatch',
    lastPropertyId: const obx_int.IdUid(8, 4903051158098597526),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 615432495870064772),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4485176547938856775),
        name: 'owner',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8509776764539387592),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2845011411820907712),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7105869703285045905),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8401914449182871011),
        name: 'totalVolume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3746381525778729131),
        name: 'logCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4903051158098597526),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'logs',
        srcEntity: 'LogEntry',
        srcField: 'batch',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3258460803860110807),
    name: 'LogEntry',
    lastPropertyId: const obx_int.IdUid(11, 2409879774864062978),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 259656842806714057),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3018480833393639677),
        name: 'diameter',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6253536891015729498),
        name: 'length',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 607033104195117929),
        name: 'volume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6785067125998849368),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7775608596234758066),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6292438590926794467),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6120421034750751418),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6855917519966908061),
        name: 'batchId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 7549459949603585428),
        relationTarget: 'LogBatch',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8160418153423733537),
        name: 'parcelId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 7980179310958526698),
        relationTarget: 'Parcel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2409879774864062978),
        name: 'species',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 9119904791546975638),
    name: 'MapLocation',
    lastPropertyId: const obx_int.IdUid(6, 1512553072282750778),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2202155098422181246),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3244590868631914152),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 411182723433623766),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8185530635729788931),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 89958773289807447),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1512553072282750778),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1150465591501636009),
    name: 'Parcel',
    lastPropertyId: const obx_int.IdUid(12, 6454727420891196624),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1342535238101297136),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2534531305218592517),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4208430250289579226),
        name: 'polygonJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4595354318594393384),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8492246665088015340),
        name: 'cadastralMunicipality',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7306732174878860760),
        name: 'parcelNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6482780184020419380),
        name: 'owner',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4514296672018729306),
        name: 'forestTypeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1613256058478576352),
        name: 'woodAllowance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2387958365358532435),
        name: 'woodCut',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6772480910293055541),
        name: 'treesCut',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6454727420891196624),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'logs',
        srcEntity: 'LogEntry',
        srcField: 'parcel',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1599301179648303857),
    name: 'HttpCacheEntry',
    lastPropertyId: const obx_int.IdUid(6, 6352423221128131205),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2707972340378378649),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4569322675758256025),
        name: 'urlHash',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 1042657973952538395),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2414247420210179960),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4307469408138803252),
        name: 'responseBody',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4692708033838747566),
        name: 'statusCode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6352423221128131205),
        name: 'cachedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 9108835119989098066),
    name: 'ImportedOverlay',
    lastPropertyId: const obx_int.IdUid(9, 2484458391629955181),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4379128102586308085),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4470717557830539678),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2320791695681775036),
        name: 'layerName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 797178476411385614),
        name: 'geometryType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3971317127120794841),
        name: 'geometryJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1291040918249336657),
        name: 'properties',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1240497488195827897),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1035808485245402638),
        name: 'visible',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2484458391629955181),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 9108835119989098066),
    lastIndexId: const obx_int.IdUid(7, 7980179310958526698),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [
      7332073029063629073,
      2416280335665670942,
      6546084107865475637,
      3650335391562379587,
    ],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    LogBatch: obx_int.EntityDefinition<LogBatch>(
      model: _entities[0],
      toOneRelations: (LogBatch object) => [],
      toManyRelations: (LogBatch object) => {
        obx_int.RelInfo<LogEntry>.toOneBacklink(
          9,
          object.id,
          (LogEntry srcObject) => srcObject.batch,
        ): object.logs,
      },
      getId: (LogBatch object) => object.id,
      setId: (LogBatch object, int id) {
        object.id = id;
      },
      objectToFB: (LogBatch object, fb.Builder fbb) {
        final ownerOffset = object.owner == null
            ? null
            : fbb.writeString(object.owner!);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, ownerOffset);
        fbb.addOffset(2, notesOffset);
        fbb.addFloat64(3, object.latitude);
        fbb.addFloat64(4, object.longitude);
        fbb.addFloat64(5, object.totalVolume);
        fbb.addInt64(6, object.logCount);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final ownerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final totalVolumeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final logCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = LogBatch(
          id: idParam,
          owner: ownerParam,
          notes: notesParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          totalVolume: totalVolumeParam,
          logCount: logCountParam,
          createdAt: createdAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<LogBatch>(
          object.logs,
          store,
          obx_int.RelInfo<LogEntry>.toOneBacklink(
            9,
            object.id,
            (LogEntry srcObject) => srcObject.batch,
          ),
        );
        return object;
      },
    ),
    LogEntry: obx_int.EntityDefinition<LogEntry>(
      model: _entities[1],
      toOneRelations: (LogEntry object) => [object.batch, object.parcel],
      toManyRelations: (LogEntry object) => {},
      getId: (LogEntry object) => object.id,
      setId: (LogEntry object, int id) {
        object.id = id;
      },
      objectToFB: (LogEntry object, fb.Builder fbb) {
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final speciesOffset = object.species == null
            ? null
            : fbb.writeString(object.species!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.diameter);
        fbb.addFloat64(2, object.length);
        fbb.addFloat64(3, object.volume);
        fbb.addFloat64(4, object.latitude);
        fbb.addFloat64(5, object.longitude);
        fbb.addOffset(6, notesOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.batch.targetId);
        fbb.addInt64(9, object.parcel.targetId);
        fbb.addOffset(10, speciesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final diameterParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          6,
        );
        final lengthParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final volumeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final speciesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = LogEntry(
          id: idParam,
          diameter: diameterParam,
          length: lengthParam,
          volume: volumeParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          notes: notesParam,
          species: speciesParam,
          createdAt: createdAtParam,
        );
        object.batch.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.batch.attach(store);
        object.parcel.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.parcel.attach(store);
        return object;
      },
    ),
    MapLocation: obx_int.EntityDefinition<MapLocation>(
      model: _entities[2],
      toOneRelations: (MapLocation object) => [],
      toManyRelations: (MapLocation object) => {},
      getId: (MapLocation object) => object.id,
      setId: (MapLocation object, int id) {
        object.id = id;
      },
      objectToFB: (MapLocation object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.latitude);
        fbb.addFloat64(3, object.longitude);
        fbb.addInt64(4, object.typeIndex);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final longitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object =
            MapLocation(
                id: idParam,
                name: nameParam,
                latitude: latitudeParam,
                longitude: longitudeParam,
                createdAt: createdAtParam,
              )
              ..typeIndex = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                12,
                0,
              );

        return object;
      },
    ),
    Parcel: obx_int.EntityDefinition<Parcel>(
      model: _entities[3],
      toOneRelations: (Parcel object) => [],
      toManyRelations: (Parcel object) => {
        obx_int.RelInfo<LogEntry>.toOneBacklink(
          10,
          object.id,
          (LogEntry srcObject) => srcObject.parcel,
        ): object.logs,
      },
      getId: (Parcel object) => object.id,
      setId: (Parcel object, int id) {
        object.id = id;
      },
      objectToFB: (Parcel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final polygonJsonOffset = fbb.writeString(object.polygonJson);
        final parcelNumberOffset = object.parcelNumber == null
            ? null
            : fbb.writeString(object.parcelNumber!);
        final ownerOffset = object.owner == null
            ? null
            : fbb.writeString(object.owner!);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, polygonJsonOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.cadastralMunicipality);
        fbb.addOffset(5, parcelNumberOffset);
        fbb.addOffset(6, ownerOffset);
        fbb.addInt64(7, object.forestTypeIndex);
        fbb.addFloat64(8, object.woodAllowance);
        fbb.addFloat64(9, object.woodCut);
        fbb.addInt64(10, object.treesCut);
        fbb.addOffset(11, notesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final cadastralMunicipalityParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 12);
        final parcelNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final ownerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final woodAllowanceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final woodCutParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final treesCutParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final polygonJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object =
            Parcel(
                id: idParam,
                name: nameParam,
                createdAt: createdAtParam,
                cadastralMunicipality: cadastralMunicipalityParam,
                parcelNumber: parcelNumberParam,
                owner: ownerParam,
                notes: notesParam,
                woodAllowance: woodAllowanceParam,
                woodCut: woodCutParam,
                treesCut: treesCutParam,
                polygonJson: polygonJsonParam,
              )
              ..forestTypeIndex = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                18,
                0,
              );
        obx_int.InternalToManyAccess.setRelInfo<Parcel>(
          object.logs,
          store,
          obx_int.RelInfo<LogEntry>.toOneBacklink(
            10,
            object.id,
            (LogEntry srcObject) => srcObject.parcel,
          ),
        );
        return object;
      },
    ),
    HttpCacheEntry: obx_int.EntityDefinition<HttpCacheEntry>(
      model: _entities[4],
      toOneRelations: (HttpCacheEntry object) => [],
      toManyRelations: (HttpCacheEntry object) => {},
      getId: (HttpCacheEntry object) => object.id,
      setId: (HttpCacheEntry object, int id) {
        object.id = id;
      },
      objectToFB: (HttpCacheEntry object, fb.Builder fbb) {
        final urlHashOffset = fbb.writeString(object.urlHash);
        final urlOffset = fbb.writeString(object.url);
        final responseBodyOffset = fbb.writeString(object.responseBody);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, urlHashOffset);
        fbb.addOffset(2, urlOffset);
        fbb.addOffset(3, responseBodyOffset);
        fbb.addInt64(4, object.statusCode);
        fbb.addInt64(5, object.cachedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final urlHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final responseBodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final statusCodeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final cachedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = HttpCacheEntry(
          id: idParam,
          urlHash: urlHashParam,
          url: urlParam,
          responseBody: responseBodyParam,
          statusCode: statusCodeParam,
          cachedAt: cachedAtParam,
        );

        return object;
      },
    ),
    ImportedOverlay: obx_int.EntityDefinition<ImportedOverlay>(
      model: _entities[5],
      toOneRelations: (ImportedOverlay object) => [],
      toManyRelations: (ImportedOverlay object) => {},
      getId: (ImportedOverlay object) => object.id,
      setId: (ImportedOverlay object, int id) {
        object.id = id;
      },
      objectToFB: (ImportedOverlay object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final layerNameOffset = fbb.writeString(object.layerName);
        final geometryTypeOffset = fbb.writeString(object.geometryType);
        final geometryJsonOffset = fbb.writeString(object.geometryJson);
        final propertiesOffset = object.properties == null
            ? null
            : fbb.writeString(object.properties!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, layerNameOffset);
        fbb.addOffset(3, geometryTypeOffset);
        fbb.addOffset(4, geometryJsonOffset);
        fbb.addOffset(5, propertiesOffset);
        fbb.addInt64(6, object.colorValue);
        fbb.addBool(7, object.visible);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final layerNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final geometryTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final geometryJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final propertiesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final colorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final visibleParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object = ImportedOverlay(
          id: idParam,
          name: nameParam,
          layerName: layerNameParam,
          geometryType: geometryTypeParam,
          geometryJson: geometryJsonParam,
          properties: propertiesParam,
          colorValue: colorValueParam,
          visible: visibleParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [LogBatch] entity fields to define ObjectBox queries.
class LogBatch_ {
  /// See [LogBatch.id].
  static final id = obx.QueryIntegerProperty<LogBatch>(
    _entities[0].properties[0],
  );

  /// See [LogBatch.owner].
  static final owner = obx.QueryStringProperty<LogBatch>(
    _entities[0].properties[1],
  );

  /// See [LogBatch.notes].
  static final notes = obx.QueryStringProperty<LogBatch>(
    _entities[0].properties[2],
  );

  /// See [LogBatch.latitude].
  static final latitude = obx.QueryDoubleProperty<LogBatch>(
    _entities[0].properties[3],
  );

  /// See [LogBatch.longitude].
  static final longitude = obx.QueryDoubleProperty<LogBatch>(
    _entities[0].properties[4],
  );

  /// See [LogBatch.totalVolume].
  static final totalVolume = obx.QueryDoubleProperty<LogBatch>(
    _entities[0].properties[5],
  );

  /// See [LogBatch.logCount].
  static final logCount = obx.QueryIntegerProperty<LogBatch>(
    _entities[0].properties[6],
  );

  /// See [LogBatch.createdAt].
  static final createdAt = obx.QueryDateProperty<LogBatch>(
    _entities[0].properties[7],
  );

  /// see [LogBatch.logs]
  static final logs = obx.QueryBacklinkToMany<LogEntry, LogBatch>(
    LogEntry_.batch,
  );
}

/// [LogEntry] entity fields to define ObjectBox queries.
class LogEntry_ {
  /// See [LogEntry.id].
  static final id = obx.QueryIntegerProperty<LogEntry>(
    _entities[1].properties[0],
  );

  /// See [LogEntry.diameter].
  static final diameter = obx.QueryDoubleProperty<LogEntry>(
    _entities[1].properties[1],
  );

  /// See [LogEntry.length].
  static final length = obx.QueryDoubleProperty<LogEntry>(
    _entities[1].properties[2],
  );

  /// See [LogEntry.volume].
  static final volume = obx.QueryDoubleProperty<LogEntry>(
    _entities[1].properties[3],
  );

  /// See [LogEntry.latitude].
  static final latitude = obx.QueryDoubleProperty<LogEntry>(
    _entities[1].properties[4],
  );

  /// See [LogEntry.longitude].
  static final longitude = obx.QueryDoubleProperty<LogEntry>(
    _entities[1].properties[5],
  );

  /// See [LogEntry.notes].
  static final notes = obx.QueryStringProperty<LogEntry>(
    _entities[1].properties[6],
  );

  /// See [LogEntry.createdAt].
  static final createdAt = obx.QueryDateProperty<LogEntry>(
    _entities[1].properties[7],
  );

  /// See [LogEntry.batch].
  static final batch = obx.QueryRelationToOne<LogEntry, LogBatch>(
    _entities[1].properties[8],
  );

  /// See [LogEntry.parcel].
  static final parcel = obx.QueryRelationToOne<LogEntry, Parcel>(
    _entities[1].properties[9],
  );

  /// See [LogEntry.species].
  static final species = obx.QueryStringProperty<LogEntry>(
    _entities[1].properties[10],
  );
}

/// [MapLocation] entity fields to define ObjectBox queries.
class MapLocation_ {
  /// See [MapLocation.id].
  static final id = obx.QueryIntegerProperty<MapLocation>(
    _entities[2].properties[0],
  );

  /// See [MapLocation.name].
  static final name = obx.QueryStringProperty<MapLocation>(
    _entities[2].properties[1],
  );

  /// See [MapLocation.latitude].
  static final latitude = obx.QueryDoubleProperty<MapLocation>(
    _entities[2].properties[2],
  );

  /// See [MapLocation.longitude].
  static final longitude = obx.QueryDoubleProperty<MapLocation>(
    _entities[2].properties[3],
  );

  /// See [MapLocation.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<MapLocation>(
    _entities[2].properties[4],
  );

  /// See [MapLocation.createdAt].
  static final createdAt = obx.QueryDateProperty<MapLocation>(
    _entities[2].properties[5],
  );
}

/// [Parcel] entity fields to define ObjectBox queries.
class Parcel_ {
  /// See [Parcel.id].
  static final id = obx.QueryIntegerProperty<Parcel>(
    _entities[3].properties[0],
  );

  /// See [Parcel.name].
  static final name = obx.QueryStringProperty<Parcel>(
    _entities[3].properties[1],
  );

  /// See [Parcel.polygonJson].
  static final polygonJson = obx.QueryStringProperty<Parcel>(
    _entities[3].properties[2],
  );

  /// See [Parcel.createdAt].
  static final createdAt = obx.QueryDateProperty<Parcel>(
    _entities[3].properties[3],
  );

  /// See [Parcel.cadastralMunicipality].
  static final cadastralMunicipality = obx.QueryIntegerProperty<Parcel>(
    _entities[3].properties[4],
  );

  /// See [Parcel.parcelNumber].
  static final parcelNumber = obx.QueryStringProperty<Parcel>(
    _entities[3].properties[5],
  );

  /// See [Parcel.owner].
  static final owner = obx.QueryStringProperty<Parcel>(
    _entities[3].properties[6],
  );

  /// See [Parcel.forestTypeIndex].
  static final forestTypeIndex = obx.QueryIntegerProperty<Parcel>(
    _entities[3].properties[7],
  );

  /// See [Parcel.woodAllowance].
  static final woodAllowance = obx.QueryDoubleProperty<Parcel>(
    _entities[3].properties[8],
  );

  /// See [Parcel.woodCut].
  static final woodCut = obx.QueryDoubleProperty<Parcel>(
    _entities[3].properties[9],
  );

  /// See [Parcel.treesCut].
  static final treesCut = obx.QueryIntegerProperty<Parcel>(
    _entities[3].properties[10],
  );

  /// See [Parcel.notes].
  static final notes = obx.QueryStringProperty<Parcel>(
    _entities[3].properties[11],
  );

  /// see [Parcel.logs]
  static final logs = obx.QueryBacklinkToMany<LogEntry, Parcel>(
    LogEntry_.parcel,
  );
}

/// [HttpCacheEntry] entity fields to define ObjectBox queries.
class HttpCacheEntry_ {
  /// See [HttpCacheEntry.id].
  static final id = obx.QueryIntegerProperty<HttpCacheEntry>(
    _entities[4].properties[0],
  );

  /// See [HttpCacheEntry.urlHash].
  static final urlHash = obx.QueryStringProperty<HttpCacheEntry>(
    _entities[4].properties[1],
  );

  /// See [HttpCacheEntry.url].
  static final url = obx.QueryStringProperty<HttpCacheEntry>(
    _entities[4].properties[2],
  );

  /// See [HttpCacheEntry.responseBody].
  static final responseBody = obx.QueryStringProperty<HttpCacheEntry>(
    _entities[4].properties[3],
  );

  /// See [HttpCacheEntry.statusCode].
  static final statusCode = obx.QueryIntegerProperty<HttpCacheEntry>(
    _entities[4].properties[4],
  );

  /// See [HttpCacheEntry.cachedAt].
  static final cachedAt = obx.QueryDateProperty<HttpCacheEntry>(
    _entities[4].properties[5],
  );
}

/// [ImportedOverlay] entity fields to define ObjectBox queries.
class ImportedOverlay_ {
  /// See [ImportedOverlay.id].
  static final id = obx.QueryIntegerProperty<ImportedOverlay>(
    _entities[5].properties[0],
  );

  /// See [ImportedOverlay.name].
  static final name = obx.QueryStringProperty<ImportedOverlay>(
    _entities[5].properties[1],
  );

  /// See [ImportedOverlay.layerName].
  static final layerName = obx.QueryStringProperty<ImportedOverlay>(
    _entities[5].properties[2],
  );

  /// See [ImportedOverlay.geometryType].
  static final geometryType = obx.QueryStringProperty<ImportedOverlay>(
    _entities[5].properties[3],
  );

  /// See [ImportedOverlay.geometryJson].
  static final geometryJson = obx.QueryStringProperty<ImportedOverlay>(
    _entities[5].properties[4],
  );

  /// See [ImportedOverlay.properties].
  static final properties = obx.QueryStringProperty<ImportedOverlay>(
    _entities[5].properties[5],
  );

  /// See [ImportedOverlay.colorValue].
  static final colorValue = obx.QueryIntegerProperty<ImportedOverlay>(
    _entities[5].properties[6],
  );

  /// See [ImportedOverlay.visible].
  static final visible = obx.QueryBooleanProperty<ImportedOverlay>(
    _entities[5].properties[7],
  );

  /// See [ImportedOverlay.createdAt].
  static final createdAt = obx.QueryDateProperty<ImportedOverlay>(
    _entities[5].properties[8],
  );
}
