[platformio]
default_envs = t1000e_rtk
boards_dir = boards

[env:t1000e_rtk]
platform = nordicnrf52
platform_packages =
  framework-arduinoadafruitnrf52 @ 1.10700.0
board = tracker-t1000-e
framework = arduino
monitor_speed = 115200
board_build.ldscript = boards/nrf52840_s140_v7.ld
build_flags =
  -D NRF52_PLATFORM
  -D CFG_DEBUG=0
  -I src
lib_deps =
  SPI
  Wire
upload_protocol = nrfutil

